trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Checkout the code from your repository (this pulls in the .tf files as well)
  - checkout: self

  # Install Terraform
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.5.0'

  # Initialize Terraform
  - task: TerraformTaskV1@0
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/08_aks_terraform'
      backendServiceArm: 'azure-cli-2024-10-14-06-24-51'
      backendAzureRmResourceGroupName: 'rg-containerapps-workshop1'
      backendAzureRmStorageAccountName: 'aksstorage001978'
      backendAzureRmContainerName: 'blobcontainer'
      backendAzureRmKey: 'terraform.tfstate'

  # Terraform Plan
  - task: TerraformTaskV1@0
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/08_aks_terraform'
      commandOptions: '-var-file=variables.tf -out=plan.out'
      environmentServiceNameAzureRM: 'azure-cli-2024-10-14-06-24-51'

  # Terraform Apply
  - task: TerraformTaskV1@0
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/08_aks_terraform'
      commandOptions: '-auto-approve plan.out'
      environmentServiceNameAzureRM: 'azure-cli-2024-10-14-06-24-51'
