trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Define any additional variables if needed

steps:
  # Checkout the code from your repository (this pulls in the .tf files as well)
  - checkout: self

  # Install Terraform
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.5.0'

  # Initialize Terraform
  - task: TerraformTaskV1@0
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'azure-cli-2024-10-14-06-24-51'  # Ensure this service connection exists
      backendAzureRmResourceGroupName: 'rg-containerapps-workshop1'
      workingDirectory: '$(System.DefaultWorkingDirectory)'  # Specify working directory

  # Terraform Plan
  - task: TerraformTaskV1@0
    inputs:
      provider: 'azurerm'
      command: 'plan'
      commandOptions: '-var-file="terraform.tfvars" -out=plan.out'
      environmentServiceNameAzureRM: 'azure-cli-2024-10-14-06-24-51'

  # Terraform Apply
  - task: TerraformTaskV1@0
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '-auto-approve plan.out'
      environmentServiceNameAzureRM: 'azure-cli-2024-10-14-06-24-51'
